# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Build
    displayName: Build image
    pool:
      name: LocalAGPL
      Image: LocalMachine
    jobs:  
    - job: Build
      displayName: Build and push Docker image
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'ContainerDReg'
          command: 'build'
          Dockerfile: '**/Dockerfile'
