# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: LocalAGPL
  Image: LocalMachine

stages:
  - stage: Build
    displayName: Build image
    jobs:  
    - job: Build
      displayName: Build and push Docker image
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'RegistryJavaApp-azure-container-registry'
          command: 'build'
          Dockerfile: '**/Dockerfile'
      - task: Docker@2
        inputs:
          containerRegistry: 'RegistryJavaApp-azure-container-registry'
          command: 'push'
