# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: LocalAGPL
      Image: LocalMachine
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/main/resources/Dockerfile'
        tags: |
          $(tag)

    # - task: CopyFiles@2
    #   inputs:
    #     SourceFolder: '$(agent.builddirectory)'
    #     Contents: '**'
    #     TargetFolder: '$(build.artifactstagingdirectory)'
    
    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     ArtifactName: 'drop'
    #     publishLocation: 'Container'