# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  name: LocalAGPL
  Image: LocalMachine

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'RegistryJavaApp-azure-container-registry'
    command: 'start'